name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  format_and_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: extractions/setup-just@v1

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - run: pip install -e .[dev]
      - run: just checks

  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: extractions/setup-just@v1

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - run: pip install -e .[dev]
      - run: just tests
